experiment_name: batch_exp
run_name: default
seed: 42
verbose: true

data_contents: 'tumor'

model: {
  class: GradCAM,
  kwargs: {}
}
backbone: {
  class: VGG,
  kwargs: {}
}
classifier: {
  class: MLP,
  kwargs: {
    layers: [128, 128]
  }
}
projection: duplicate
augment:
  - geometric
  - color
  # - blur
  # - erasing

batch_size: 32
epochs: 25
lr: 1e-3
wd: 1e-4
threshold: 0.7



